language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd application
  - yarn install &&
    yarn test &&
    yarn build
after_script:
  - cd application
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls